### ISSUE TITLE
Calling .setData  does not clear the DOM and all previous data

### ISSUE THREAD

**Issue by StanislavNikolov** [winetree94/VanillaRecyclerView#6]
Steps to reproduce:

1. Make an empty recyclerView.
2. call recyclerView.setData(array_1);
3. scroll down a little bit
4. call recyclerView.setData(array_2);

Expected behaviour:
All of the data from array_1 will disappear from the DOM.
Actual behaviour:
Some of the data of array_1 stays in the DOM, overlayed with the data from array_2

![CleanShot 2023-02-21 at 14 48 00](https://user-images.githubusercontent.com/10270328/220348881-727c3adb-cffe-4347-865a-12043d711f6e.png)

**Comment by winetree94** [comment]
thanks for your reporting.

If you install version [1.1.10](https://www.npmjs.com/package/vanilla-recycler-view/v/1.1.10), the issue will be resolved
